var fs=require("fs")
fs.writeFileSync("t1.txt","Hello")
const data = fs.readFileSync("t1.txt")
console.log(data)
console.log(data.toString())
fs.appendFileSync("t1.txt","\n New catch ")
fs.renameSync("t1.txt","t2.txt")
fs.unlinkSync("t2.txt")
console.log("done")
fs.mk("temp")